#!/bin/bash

echo installing "bunto switcher"...

# Cоздаем папку приложения если еще не существует
# Очищаем содержимое если папка уже существует
mkdir -p /usr/share/bunto
rm -rf /usr/share/bunto/*

# Копируем файлы приложения
cp -R ./* /usr/share/bunto/
cp ./bunto.desktop /usr/share/applications/

# Устанавливаем зависимости
# appindicator
sudo dnf install gnome-shell-extension-appindicator
gnome-extensions enable appindicatorsupport@rgcjonas.gmail.com
# релогин или перезагрузка может потребоваться после первого шага

# evdev
sudo dnf makecache
sudo dnf install python3-evdev.x86_64

# dbus-x11
sudo dnf install dbus-x11 -y

echo completed...
