#!/bin/bash

echo installing "bunto switcher"...

# Cоздаем папку приложения если еще не существует
# Очищаем содержимое если папка уже существует
mkdir -p /usr/share/bunto
rm -rf /usr/share/bunto/*

# Копируем файлы приложения
cp -R ./* /usr/share/bunto/
cp ./bunto.desktop /usr/share/applications/

# Устанавливаем зависимости
yes | pip install evdev
yes | pip install xkbgroup
sudo dnf install dbus-x11 -y

echo completed...
