#!/bin/bash

echo Удаляю bunto switcher...

# Удаляем папку.
echo Удаляю папку приложения...
rm -rf /usr/share/bunto

# Удаляем из обзора приложений.
echo Удаляю из обзора приложений...
rm -rf /usr/share/applications/bunto.desktop

# Удаляем из автозапуска.
echo Удаляю из автозапуска...
rm -rf /home/$SUDO_USER/.config/autostart/bunto.desktop

# Удаляем разрешение из sudoers.
echo Удаляю разрешение из sudoers...
sudo sed -i "/## Exception for Bunto Switcher/d" /etc/sudoers
sudo sed -i "/$SUDO_USER ALL=(ALL) NOPASSWD: \/usr\/bin\/nice -n -18 python \/usr\/share\/bunto\/switcher.py/d" /etc/sudoers

echo Готово!...