#('EV_SYN', 0):
EV_SYNS = [
('SYN_REPORT', 0), 
('SYN_CONFIG', 1), 
('?', 4), 
('?', 17), 
('?', 21)] 

#('EV_KEY', 1):
EV_KEYS = [
('KEY_ESC',         'esc',          'esc',          'esc',          'esc',          1,          0),
('KEY_1',           '1',            '!',            '1',            '!',            2,          1), 
('KEY_2',           '2',            '@',            '2',            '"',            3,          1), 
('KEY_3',           '3',            '#',            '3',            '№',            4,          1), 
('KEY_4',           '4',            '$',            '4',            ';',            5,          1),  
('KEY_5',           '5',            '%',            '5',            '%',            6,          1),
('KEY_6',           '6',            '^',            '6',            ':',            7,          1), 
('KEY_7',           '7',            '&',            '7',            '?',            8,          1), 
('KEY_8',           '8',            '*',            '8',            '*',            9,          1), 
('KEY_9',           '9',            '(',            '9',            '(',            10,         1), 
('KEY_0',           '0',            ')',            '0',            ')',            11,         1), 
('KEY_MINUS',       '-',            '_',            '-',            '_',            12,         1), 
('KEY_EQUAL',       '=',            '+',            '=',            '+',            13,         1), 
('KEY_BACKSPACE',   'backspace',    'backspace',    'backspace',    'backspace',    14,         0), 
('KEY_TAB',         'tab',          'tab',          'tab',          'tab',          15,         1), 
('KEY_Q',           'q',            'Q',            'й',            'Й',            16,         1), 
('KEY_W',           'w',            'W',            'ц',            'Ц',            17,         1), 
('KEY_E',           'e',            'E',            'у',            'У',            18,         1), 
('KEY_R',           'r',            'R',            'к',            'К',            19,         1), 
('KEY_T',           't',            'T',            'е',            'Е',            20,         1), 
('KEY_Y',           'y',            'Y',            'н',            'Н',            21,         1), 
('KEY_U',           'u',            'U',            'г',            'Г',            22,         1), 
('KEY_I',           'i',            'I',            'ш',            'Ш',            23,         1), 
('KEY_O',           'o',            'O',            'щ',            'Щ',            24,         1), 
('KEY_P',           'p',            'P',            'з',            'З',            25,         1), 
('KEY_LEFTBRACE',   '[',            '{',            'х',            'Х',            26,         1), 
('KEY_RIGHTBRACE',  ']',            '}',            'ъ',            'Ъ',            27,         1), 
('KEY_ENTER',       'enter',        'enter',        'enter',        'enter',        28,         0), 
('KEY_LEFTCTRL',    'ctrl_left',    'ctrl_left',    'ctrl_left',    'ctrl_left',    29,         0),
('KEY_A',           'a',            'A',            'ф',            'Ф',            30,         1), 
('KEY_S',           's',            'S',            'ы',            'Ы',            31,         1), 
('KEY_D',           'd',            'D',            'в',            'В',            32,         1), 
('KEY_F',           'f',            'F',            'а',            'А',            33,         1), 
('KEY_G',           'g',            'G',            'п',            'П',            34,         1), 
('KEY_H',           'h',            'H',            'р',            'Р',            35,         1), 
('KEY_J',           'j',            'J',            'о',            'О',            36,         1), 
('KEY_K',           'k',            'K',            'л',            'Л',            37,         1), 
('KEY_L',           'l',            'L',            'д',            'Д',            38,         1), 
('KEY_SEMICOLON',   ';',            ':',            'ж',            'Ж',            39,         1), 
('KEY_APOSTROPHE',  '\'',           '"',            'э',            'Э',            40,         1), 
('KEY_GRAVE',       '`',            '~',            'ё',            'Ё',            41,         1), 
('KEY_LEFTSHIFT',   'shift_left',   'shift_left',   'shift_left',   'shift_left',   42,         0), 
('KEY_BACKSLASH',   '\\',           '|',            '\\',           '/',            43,         1), 
('KEY_Z',           'z',            'Z',            'я',            'Я',            44,         1), 
('KEY_X',           'x',            'X',            'ч',            'Ч',            45,         1), 
('KEY_C',           'c',            'C',            'с',            'С',            46,         1), 
('KEY_V',           'v',            'V',            'м',            'М',            47,         1), 
('KEY_B',           'b',            'B',            'и',            'И',            48,         1), 
('KEY_N',           'n',            'N',            'т',            'Т',            49,         1), 
('KEY_M',           'm',            'M',            'ь',            'Ь',            50,         1), 
('KEY_COMMA',       ',',            '<',            'б',            'Б',            51,         1), 
('KEY_DOT',         '.',            '>',            'ю',            'Ю',            52,         1), 
('KEY_SLASH',       '/',            '?',            '.',            ',',            53,         1), 
('KEY_RIGHTSHIFT',  'shift_right',  'shift_right',  'shift_right',  'shift_right',  54,         0), 
('KEY_KPASTERISK',  '*',            '*',            '*',            '*',            55,         1), 
('KEY_LEFTALT',     'alt_left',     'alt_left',     'alt_left',     'alt_left',     56,         0), 
('KEY_SPACE',       ' ',            ' ',            ' ',            ' ',            57,         1), 
('KEY_CAPSLOCK',    'caps_lock',    'caps_lock',    'caps_lock',    'caps_lock',    58,         0), 
('KEY_F1',          'f1',           'f1',           'f1',           'f1',           59,         0), 
('KEY_F2',          'f2',           'f2',           'f2',           'f2',           60,         0), 
('KEY_F3',          'f3',           'f3',           'f3',           'f3',           61,         0), 
('KEY_F4',          'f4',           'f4',           'f4',           'f4',           62,         0), 
('KEY_F5',          'f5',           'f5',           'f5',           'f5',           63,         0), 
('KEY_F6',          'f6',           'f6',           'f6',           'f6',           64,         0), 
('KEY_F7',          'f7',           'f7',           'f7',           'f7',           65,         0), 
('KEY_F8',          'f8',           'f8',           'f8',           'f8',           66,         0), 
('KEY_F9',          'f9',           'f9',           'f9',           'f9',           67,         0), 
('KEY_F10',         'f10',          'f10',          'f10',          'f10',          68,         0), 
('KEY_NUMLOCK',     'num_lock',     'num_lock',     'num_lock',     'num_lock',     69,         0), 
('KEY_SCROLLLOCK',  'scroll_lock',  'scroll_lock',  'scroll_lock',  'scroll_lock',  70,         0), 
('KEY_KP7',         '7',            '7',            '7',            '7',            71,         1), 
('KEY_KP8',         '8',            '8',            '8',            '8',            72,         1), 
('KEY_KP9',         '9',            '9',            '9',            '9',            73,         1), 
('KEY_KPMINUS',     '-',            '-',            '-',            '-',            74,         1), 
('KEY_KP4',         '4',            '4',            '4',            '4',            75,         1), 
('KEY_KP5',         '5',            '5',            '5',            '5',            76,         1), 
('KEY_KP6',         '6',            '6',            '6',            '6',            77,         1), 
('KEY_KPPLUS',      '+',            '+',            '+',            '+',            78,         1), 
('KEY_KP1',         '1',            '1',            '1',            '1',            79,         1), 
('KEY_KP2',         '2',            '2',            '2',            '2',            80,         1), 
('KEY_KP3',         '3',            '3',            '3',            '3',            81,         1), 
('KEY_KP0',         '0',            '0',            '0',            '0',            82,         1), 
('KEY_KPDOT',       '.',            '.',            '.',            '.',            83,         1), 
('KEY_ZENKAKUHANKAKU', '',          '',             '',             '',             85,         1), 
('KEY_102ND',       '',             '',             '',             '',             86,         1), 
('KEY_F11',         'f11',          'f11',          'f11',          'f11',          87,         0), 
('KEY_F12',         'f12',          'f12',          'f12',          'f12',          88,         0), 
('KEY_RO',          '',             '',             '',             '',             89,         0), 
('KEY_KATAKANA',    '',             '',             '',             '',             90,         0),
('KEY_HIRAGANA',    '',             '',             '',             '',             91,         0),
('KEY_HENKAN',      '',             '',             '',             '',             92,         0),
('KEY_KATAKANAHIRAGANA', '',        '',             '',             '',             93,         0),
('KEY_MUHENKAN',    '',             '',             '',             '',             94,         0),
('KEY_KPJPCOMMA',   '',             '',             '',             '',             95,         0),
('KEY_KPENTER',     'enter',        'enter',        'enter',        'enter',        96,         0),
('KEY_RIGHTCTRL',   'ctrl_right',   'ctrl_right',   'ctrl_right',   'ctrl_right',   97,         0),
('KEY_KPSLASH',     '/',            '/',            '/',            '/',            98,         1),
('KEY_SYSRQ',       'print_screen', 'print_screen', 'print_screen', 'print_screen', 99,         0), 
('KEY_RIGHTALT',    'alt_right',    'alt_right',    'alt_right',    'alt_right',    100,        0), 
('KEY_HOME',        'home',         'home',         'home',         'home',         102,        0), 
('KEY_UP',          'up',           'up',           'up',           'up',           103,        0), 
('KEY_PAGEUP',      'page_up',      'page_up',      'page_up',      'page_up',      104,        0), 
('KEY_LEFT',        'left',         'left',         'left',         'left',         105,        0),
('KEY_RIGHT',       'right',        'right',        'right',        'right',        106,        0),
('KEY_END',         'end',          'end',          'end',          'end',          107,        0),
('KEY_DOWN',        'down',         'down',         'down',         'down',         108,        0), 
('KEY_PAGEDOWN',    'page_down',    'page_down',    'page_down',    'page_down',    109,        0), 
('KEY_INSERT',      'insert',       'insert',       'insert',       'insert',       110,        0), 
('KEY_DELETE',      'delete',       'delete',       'delete',       'delete',       111,        0), 
#(['KEY_MIN_INTERESTING', 'KEY_MUTE'], '', 113),
('KEY_VOLUMEDOWN',  '',             '',             '',             '',             114,        0), 
('KEY_VOLUMEUP',    '',             '',             '',             '',             115,        0), 
('KEY_POWER',       '',             '',             '',             '',             116,        0), 
('KEY_KPEQUAL',     '',             '',             '',             '',             117,        0), 
('KEY_PAUSE',       'pause',        'pause',        'pause',        'pause',        119,        0),
('KEY_KPCOMMA',     '',             '',             '',             '',             121,        0), 
#(['KEY_HANGEUL', 'KEY_HANGUEL'], '', 122), 
('KEY_HANJA',       '',             '',             '',             '',             123,        0), 
('KEY_YEN',         '',             '',             '',             '',             124,        0), 
('KEY_LEFTMETA',    'win_left',     'win_left',     'win_left',     'win_left',     125,        0), 
('KEY_RIGHTMETA',   'win_right',    'win_right',    'win_right',    'win_right',    126,        0), 
('KEY_COMPOSE',     'menu',         'menu',         'menu',         'menu',         127,        0), 
('KEY_STOP',        '',             '',             '',             '',             128,        0), 
('KEY_AGAIN',       '',             '',             '',             '',             129,        0), 
('KEY_PROPS',       '',             '',             '',             '',             130,        0), 
('KEY_UNDO',        '',             '',             '',             '',             131,        0), 
('KEY_FRONT',       '',             '',             '',             '',             132,        0), 
('KEY_COPY',        '',             '',             '',             '',             133,        0), 
('KEY_OPEN',        '',             '',             '',             '',             134,        0), 
('KEY_PASTE',       '',             '',             '',             '',             135,        0), 
('KEY_FIND',        '',             '',             '',             '',             136,        0), 
('KEY_CUT',         '',             '',             '',             '',             137,        0), 
('KEY_HELP',        '',             '',             '',             '',             138,        0), 
('KEY_F13',         '',             '',             '',             '',             183,        0), 
('KEY_F14',         '',             '',             '',             '',             184,        0), 
('KEY_F15',         '',             '',             '',             '',             185,        0), 
('KEY_F16',         '',             '',             '',             '',             186,        0), 
('KEY_F17',         '',             '',             '',             '',             187,        0), 
('KEY_F18',         '',             '',             '',             '',             188,        0), 
('KEY_F19',         '',             '',             '',             '',             189,        0), 
('KEY_F20',         '',             '',             '',             '',             190,        0), 
('KEY_F21',         '',             '',             '',             '',             191,        0), 
('KEY_F22',         '',             '',             '',             '',             192,        0), 
('KEY_F23',         '',             '',             '',             '',             193,        0), 
('KEY_F24',         '',             '',             '',             '',             194,        0), 
('KEY_UNKNOWN',     '',             '',             '',             '',             240,        0)]

#('EV_MSC', 4): 
EV_MSCS = [
('MSC_SCAN', 4)]

#('EV_LED', 17)
EV_LEDS = [
('LED_NUML', 0), 
('LED_CAPSL', 1), 
('LED_SCROLLL', 2), 
('LED_COMPOSE', 3), 
('LED_KANA', 4)]

# ('VIS_KEYS', X)
VIS_KEYS = [x[5] for x in EV_KEYS if x[6]]